DROP TABLE IF EXISTS MOVIES;
  
CREATE TABLE MOVIES (
  Id INT AUTO_INCREMENT  PRIMARY KEY,
  MovieName VARCHAR(250) NOT NULL,
  Director VARCHAR(250) NOT NULL,
  Budget VARCHAR(250),
  Year VARCHAR(4),
  Rating VARCHAR(3)
);